<a href="https://colab.research.google.com/github/gtsiwicki/Math311-Linear-Algebra/blob/main/Gannon_Siwicki_Gram_Schmidt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gram Schmidt Orthogonalization Process




In [ ]:
import numpy as np

### Vector Operations

*   Dot Product
*   Normalization - size of a vector
*   Subtract / Add
*   Scale
*   Create Vectors

In [ ]:
# create vectors

v1 = np.array([[0],
               [3],
               [-3],
               [0]])
v1

array([[ 0],
       [ 3],
       [-3],
       [ 0]])

In [ ]:
#Checking Operations
print(v1+1)
print(" ")
print(v1*5)

[[ 1]
 [ 4]
 [-2]
 [ 1]]
 
[[  0]
 [ 15]
 [-15]
 [  0]]


In [ ]:
#Trying dot prodcuts
dot = sum(v1*v1)
dot


array([18])

In [ ]:
#Finding the norm
np.linalg.norm(v1)

np.float64(4.242640687119285)

# Gram Schmidt Process for 4 Vectors

In [ ]:
#Creating the Vectors
v1 = np.array([0,3,-3,0])
v2 = np.array([2,6,-2,2])
v3 = np.array([-2,1,-3,0])
v4 = np.array([2,-4,-2,-4])

### Processing The First Vector

In [ ]:
#Finding u1
u1 = v1 / np.linalg.norm(v1)
u1

array([ 0.        ,  0.70710678, -0.70710678,  0.        ])

In [ ]:
#Checking Size
print(np.sqrt(u1.dot(u1)))

1.0


### Processing The Second Vector

In [ ]:
#Finding t2
t2 = v2 - v2.dot(u1) *u1
print(t2)

#Normalizing

u2 = t2 / np.linalg.norm(t2)
print(u2)

[2. 2. 2. 2.]
[0.5 0.5 0.5 0.5]


In [ ]:
#Checking
print("Size= ",np.sqrt(u2.dot(u2)))

print("Dot product= ", u1.dot(u2))

Size=  1.0
Dot product=  -3.3306690738754696e-16


### Processing Thrid Vector

In [ ]:
#Finding t3
t3 = v3 - v3.dot(u1) *u1 - v3.dot(u2) *u2
print(t3)

#Normalizing

u3 = t3 / np.linalg.norm(t3)
print(u3)

[-1.00000000e+00 -4.44089210e-16  1.33226763e-15  1.00000000e+00]
[-7.07106781e-01 -3.14018492e-16  9.42055475e-16  7.07106781e-01]


In [ ]:
#Checking
print("Size= ",np.sqrt(u3.dot(u3)))

print("Dot product= ", u3.dot(u1))
print("Dot product= ", u3.dot(u2))

Size=  0.9999999999999999
Dot product=  -8.881784197001252e-16
Dot product=  6.106226635438361e-16


### Processing Fourth Vector

In [ ]:
#Finding t4
t4 = v4 - v4.dot(u1) *u1 - v4.dot(u2) *u2 - v4.dot(u3) *u3
print(t4)

#Normalizing

u4 = t4 / np.linalg.norm(t4)
print(u4)

[ 1. -1. -1.  1.]
[ 0.5 -0.5 -0.5  0.5]


In [ ]:
#Checking
print("Size = ",np.sqrt(u4.dot(u4)))

print("Dot product = ", u4.dot(u1))
print("Dot product = ", u4.dot(u2))
print("Dot product = ", u4.dot(u3))

Size =  0.9999999999999999
Dot product =  -2.4424906541753444e-15
Dot product =  1.1657341758564144e-15
Dot product =  5.551115123125783e-17


## All Nice Unit Vectors

In [ ]:
print("u1 = ", u1)
print("u2 = ", u2)
print("u3 = ", u3)
print("u4 = ", u4)

u1 =  [ 0.          0.70710678 -0.70710678  0.        ]
u2 =  [0.5 0.5 0.5 0.5]
u3 =  [-7.07106781e-01 -3.14018492e-16  9.42055475e-16  7.07106781e-01]
u4 =  [ 0.5 -0.5 -0.5  0.5]
